### ISSUE TITLE
actualmente hay parrafos que llevan imagen pero no texto

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#10]
http://quartiersdumonde.org/fra/qdm/info.php?id=70
¿como podemos hacer?

**Comment by migueldiaz** [comment]
Para poder meter parrafos asi, solo hay que desactivar la validacion en parrafo.rb.
De todas formas ahora que hay imagen mini, puede ponerse la imagen existente como imagen mini del parrafo anterior, ya esta familia que se piense como manejar las fotos

**Comment by migueldiaz** [comment]
Cierro el issue y abro añadir imagenes a página
