### ISSUE TITLE
remodelación de asociación

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#101]
secciones: visión, enfoque, actividades,los protagonistaas, documentación
cada sección tiene las paginas correspondientes
las unicas que no son parrafos+fotos serían contacto y los socios y la documentación
la documentación es como en jeunes y femmes
- Visión –>esto es una seccion con una sola pagina
- Enfoque ->  seccion con varias paginas
  La equidad de género
  El trabajo en red 
  Les metodologías participativas 
- Actividades->  seccion con varias paginas
  Animación de los redes
  Formaciones metodológicas (texto de presentación + lista de las formaciones)
  Organización de encuentros internacionales (texto de presentación + link hasta los eventos en las paginas proyectos)
  Participación al debate ciudadano (texto de presentación + lista de participaciones con presentaciones o informes)

*L@s protagonist@s->  seccion con varias paginas
La junta directiva
El equipo de trabajo
Los comites de sistematizacion
Entidades miembros de las redes -  Socios locales
Socios institucionales y financieros
Contáctenos

*Documentacion-> seccion con paginas y subpaginas

**Comment by migueldiaz** [comment]
Añadir   actividades va a ser trivial. En el modelado mio  los asigne al sitio.Luego para asociacion dentro de sitio  solo tendremos que mostrar el enlace en la zona de administracion. En el controlador de asociation sera copiar los metodos de jeunes y femmes y remodelar el controlador de pagina.
Tendriamos que hacer vision, protagonistas y enfoque.
Puede ser menos jaleo del que parece.

**Comment by migueldiaz** [comment]
Todas las secciones hechas,
En zona de gestion pendiente retocar los enlaces de retorno y esos detallitos
En vista de asociation añadir los 3 metodos nuevos y mapearlos, sus vistas

**Comment by tangrammer** [comment]
verificada la funcionalidad de las secciones ... solo un bug!

Visión –>esto es una seccion con una sola pagina
Enfoque -> seccion con varias paginas
Actividades-> seccion con varias paginas
L@s protagonist@s-> seccion con varias paginas
Documentacion-> seccion con paginas y subpaginas

la unica que da algo de problema es protagonistas en relación a los enlaces...
cuando hago click en gestion/asociacion/protagonistas me lleva a protagonistas?id=1 en lugar de protagonistas/1 y en el boton de volver desde pagina a protagonistas me lleva a protagonistas.1

**Comment by migueldiaz** [comment]
Ya lo localice, el retorno va a protagonistas.2 , es porque el parametro tiene que ir con (:id=>2) en paginas show.
Mapeo los metodos para la vista principal y los muestro

El problema viene de haber usado el nombre en plural, en la vista de protagonistas , rails considera que es plural y en vez de show tb tenemos que usar el metodo index. Idem para el controlador pasa por index en vez de show y el path cambia.

**Comment by migueldiaz** [comment]
Asociation_controller ya tiene los nuevos campos, solo queda añadir los enlaces en el template de asociation

http://0.0.0.0:3000/asociation/vision --> Manda a la pagina
http://0.0.0.0:3000/asociation/enfoque --> Manda a la primera pagina
http://0.0.0.0:3000/asociation/protagonistas --> Manda a la primera pagina 

He commiteado la version de busquedas, si sale el conection refused: 
  <code>rake sunspot:solr:start</code>

**Comment by migueldiaz** [comment]
Subida version con enlaces en la vista de asociation, enlace corregido. Cierro la issue

**Comment by tangrammer** [comment]
que maquina!

El 25 de octubre de 2011 12:53, Miguel <
reply@reply.github.com>escribi:

> Subida version con enlaces en la vista de asociation, enlace corregido.
> Cierro la issue
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/101#issuecomment-2515567

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
