### ISSUE TITLE
editar documento existente error

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#103]
esto sale al hacer click en editar documento y después en guardar

NoMethodError in DocumentosController#update

undefined method `closed?' for nil:NilClass

**Comment by migueldiaz** [comment]
Al subir asociation se me ha colado la version con las busquedas.
<code>rake sunspot:solr:run</code>
Si no en el modelo problematico eliminar <b>searchable</b>

<pre><code>
searchable do
        text :doces
        text :docfr
        #attachment :adjunto
        
        
    end
</code></pre>

El rake, con su version numerica viene indicado en el gemfile, bundle update o bundle install deberian solucionarlo. Si no comenta

**Comment by migueldiaz** [comment]
En la ultima subida todos los searchable estan comentados , así que no debería haber más problemas. Cierro la issue
