### ISSUE TITLE
en este listado deberia aparecer el nombre del equipo

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#104]
http://localhost:3000/usuarioforos?tipo=jeunes

el problema es que solo tenemos acceso al id de equipo porque en el modelo de usuarioforo está comentado la relacion con equipo

¿esto por qué es?

class Usuarioforo < ActiveRecord::Base
 # has_one :equipo

**Comment by migueldiaz** [comment]
Modelos corregidos
Subida la version que lo corrige.
