### ISSUE TITLE
shared/pagina.html.erb

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#105]
<code>
<%parrafo.tituloes%>
<%= parrafo.method(:titulo.to_s+locale.to_s).call %>
</code>

Si no pongo la primera linea , tengo un cuelgue en la segunda. Undefined method parrafo.tituloes.
No le veo ninguna explicacion,  ¿te suena a ti alguna razón de ser de esto?
Es solo curiosidad, en produccion no ha pasadonunca

**Comment by tangrammer** [comment]
prueba con
parrafo.send(:titulo.to_s+local)

2011/10/26 Miguel <
reply@reply.github.com>

> <pre><code>
> <%parrafo.tituloes%>
>  <h2><%= parrafo.method(:titulo.to_s+locale.to_s).call %> </h2>
> </code></pre>
> 
> 
> Si no pongo la primera linea , tengo un cuelgue en la segunda. Undefined
> method parrafo.tituloes.
> No le veo ninguna explicacion,  te suena a ti alguna razn de ser de esto?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/105

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Digo, así no hace nada extraño. Ya me contaras el por qué. Cierro esto.

**Comment by tangrammer** [comment]
la verdad es que no lo tengo muy claro, debe estar relacionado con la
persistencia ActiveRecord y la carga de las relaciones y propiedades en la
renderizacin de la vista... parece que se desconectan de la persistencia e
incluso de su propia clase de objeto pasando a ser un mapa de claves y
valores, quedando algunos vacios... estuve mirando en su da y no vi la
explicacin clara pero en la invocacin dinamica de metodos existen las dos
variantes que estamos usando y la que daba error en teora es ms rpida

saludos!

2011/10/26 Miguel <
reply@reply.github.com>

> Digo, as no hace nada extrao. Ya me contaras el por qu. Cierro esto.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/105#issuecomment-2529346

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
