### ISSUE TITLE
existe la opcion de restringir las medidas de las imagenes en la subida según el modelo

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#106]
Es decir hay posibilidad de de que por ejemplo al subir las fotos de agenda tengan un remuestreo diferente a las fotos de por ejemplo presentaciones???

**Comment by migueldiaz** [comment]
Podemos hacerle su propio uploader que lo especifique, si no carrierwave tb permite definir el tamaño en la vista con :thumb en el img_tag y ahi se le indica el tamaño. Supongo que igual que :thumb que es el que trae de serie podemos hacer un :contacto y especificarlo ahi. Lo miro

**Comment by migueldiaz** [comment]
¿Es esto lo que buscas?

<pre>
 version :thumb do
    process :resize_to_fit => [100, 100]
    process :quality => 100 
  end
</pre>

**Comment by tangrammer** [comment]
y esto no se donde hay que ponerlo.... en el controller? en la vista?

El 27 de octubre de 2011 15:02, Miguel <
reply@reply.github.com>escribi:

> <code>
>  version :thumb do
>    process :resize_to_fit => [100, 100]
>    process :quality => 100
>  end
> </code>
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/106#issuecomment-2543028

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Eso se  configura en el uploader
 El 28/10/2011 09:20, "juanantonioruz" <
reply@reply.github.com>
escribi:

**Comment by migueldiaz** [comment]
Juan aqui me tienes que dar mas norte sobre que es lo que quieres.
