### ISSUE TITLE
una descripcion para la agenda "por el amor de dios"

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#107]
Miguel!
vamos a ponerle una descripción a la "pobre" de la agenda no?
da un poco de penilla 
chaooo

**Comment by migueldiaz** [comment]
A Dios también lo vamos a meter hombre, venga añado descripciones y descripcionfr

**Comment by migueldiaz** [comment]
Se puede acceder a @contacto.descripciones o fr. 
Añadido supuesto al traductor.
Añadido a formulario y a la vista de administracion.

**Comment by migueldiaz** [comment]
Ofu que ida de pinza, 
Añadido @evento.descripciones y @evento.descripcionfr
Añadido supuesto al traductor
Vistas en zona en gestión. No lo he sacado a la principal.

**Comment by migueldiaz** [comment]
Ahora creo que si, cierro esto.
