### ISSUE TITLE
Marron volador: cada documentacion puede tener varias paginas 

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#11]
HORROR!

esto se aprecia en ...

http://quartiersdumonde.org/esp/qdm/info.php?id=71

epigrafe sistematizar, al final de la pagina hay un menu de opciones que son paginas relativas a la seccion "sistematizar"

¿cómo se te ocurre que podríamos soluciarlo de la forma más, más, más sencilla posible?...

**Comment by tangrammer** [comment]
las actividades de equipo también tienen varias paginas cada subseccion!
cagoentó!

paro de editar info hasta nueva orden!

**Comment by migueldiaz** [comment]
Pagina ya tiene paginas en documentacion, añado la opcion a las paginas de equipo.
Comparado con el foro que la profundidad es ilimitada no es mucho jaleo.

-Pendiente sacar el render de los enlaces a las vistas principales.
-Contemplar el redirect del destroy para el caso de pagina de paginas

No maldigas hombre si esto a estas alturas se puede masticar

Acabo esto y lo dejo subido antes de hacer otra cosa

**Comment by migueldiaz** [comment]
Vista de jóvenes ya muestra las "subpaginas". 
Al mostrar una subpagina, el titulo comienza por un enlace a la pagina madre seguido del titulo de la subpagina

-Fallo al mostrar las actividades de los equipos se muestran las actividades de jeunes ¿Por qué? --> && @equipo.nil?

**Comment by migueldiaz** [comment]
Creo que todo funciona correctamente, cierro y subo

**Comment by tangrammer** [comment]
Impresionante tio!

2011/8/11 migueldiaz <
reply@reply.github.com>

> Creo que todo funciona correctamente, cierro y subo
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/11#issuecomment-1777730

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Hay que acabar esto :D, que yo el 16 me quiero ir una semana a Sevilla de caza
