### ISSUE TITLE
la redireccion de editar contacto de equipo en proyecto jovenes es incorrecta

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#12]
editar lo hace bien , lo único es la vista que muestra cuando confirmas la edición, creo que se va al contacto de proyeto de mujeres

este va a ser el programa más probado de la historia!

**Comment by migueldiaz** [comment]
En local pasa al contrario, creo que viene del jaleo de cuando se subio en la reedicion. sitio_id del contacto esta cruzado
Los equipos si crean su contacto automaticamente al crearlos.
Asociacion, jeunes y femmes, la primera vez. Lo suyo seria desde el phpmyadmin vaciar la tabla de contactos, rehacerla y al entrar, entrar en el orden;
1. Ver contacto de asociacion
2. Ver contacto de jeunes
3. Ver contacto de femmes.

Con el rails cambiar la clave primaria puede marearnos un ratito

**Comment by migueldiaz** [comment]
Creo que hay una solucion menos drastica, edito el formulario de contacto e intento cambiar las sitio_id cruzadas. 
Hago prueba en local y si va la hago en servidor

**Comment by migueldiaz** [comment]
Valeee, no iban por ahi los tiros , en las opciones del sitio, en vez de enviar a sitio se mostraba sitio.contacto. 

Hecho el cambio en local, en la proxima subida cierro y aplico el cambio:

<%= link_to contacto_path(:id=>@sitio)%>

lo que hay ahora:

<%= link_to contacto_path(:id=>@sitio.contacto)%>
