### ISSUE TITLE
Publicar en servidor

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#19]
Lo que suelo hacer para tener cierto orden.
Elimino la carpeta actual de quartiersrediseno, desde la propia vista de ftp, a veces es lentisimo pero se cancela y se vuelve a dar a eliminar y ya coge ritmo

Acceder por ssh
Clono el repo con:

 git clonegit://github.com/migueldiaz/quartiersRedise-o.git

Tiene que ser la url de solo lectura, si se usan las otras tenemos problemas por las claves privadas

En la vista de ftp, en el nautilus abrir la vista de panel adicional. 
En uno dejo el que he clonado y en otro el quartiersactual
Lo mas rapido es cargarse la carpeta app de quartiersactual o renombrala hasta que estes seguro de que funciona y arrastrar la del clon a su lugar (mover es instantaneo en el servidor, copiar tarda un monton a veces, si no es por consola).
 Con la carpeta public que es la que tendras que usar, no se puede hacer igual. Hay un archivo oculto . htacces que la puede liar. Lo que si puedes es reemplazar el javascript el images y los css como con app y no debe haber ningun problema.

Cuando lo tengas. Por ssh en la carpeta personal, touch quartiersactual/tmp/restart.txt

Ya deberian verse los cambios. 
Si pasa algo el log de production va bien.
Como lo que vas a tocar son las vistas, a no ser que salte algun null por algun condicional que falte no debe haber problemas, si no el log de production es bastante certero

**Comment by jaruz** [comment]
paso esta info a wiki
