### ISSUE TITLE
Revisar .gitignore

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#2]
http://help.github.com/ignore-files/

https://github.com/github/gitignore

**Comment by jaruz** [comment]
¿se sabe algo de esto?
me gustaría bajarme algunos archivos de img a /public/upload para probar galeria de fotos pero estaría bien que no se sincronizaran en repo
chaooooo

**Comment by migueldiaz** [comment]
No lo he podido comprobar, monto un repo de prueba y lo reviso, el tutorial parece rapido

**Comment by jaruz** [comment]
ya he corregido el .gitignore de la carpeta public/upload y he borrado todo
lo que haba dentro para que cada uno tenga en la carpeta local lo que
necesite

chaooooo

2011/8/18 migueldiaz <
reply@reply.github.com>

> No lo he podido comprobar, monto un repo de prueba y lo reviso, el tutorial
> parece rapido
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/2#issuecomment-1841709

## 

Juan Antonio Ruz
codigodelaimagen@gmail.com
http://codigodelaimagen.blogspot.com/

**Comment by migueldiaz** [comment]
dejame algo hombre, :P
