### ISSUE TITLE
la cague con el deploy...

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#20]
lo raro es que funciona 
http://desarrollo.quartiersdumonde.org/

y peta la asociación que es lo que realmente estoy cambiando 
http://desarrollo.quartiersdumonde.org/asociation/presentacion
## este es el error que da...

Started GET "/asociation/presentacion" for 84.122.38.96 at Thu Aug 18 01:26:50 +0200 2011
  Processing by AsociationController#presentacion as HTML
Completed   in 3ms

LoadError (Expected /home/quartier/quartiersactual/app/controllers/asociacion.rb to define Asociacion):
##   app/controllers/asociation_controller.rb:22:in `presentacion'

ofuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu

PD: el .htaccess lo he subido al git para que no se nos olvide más

**Comment by tangrammer** [comment]
no te estreses que si no se enseña mañana no pasa na'
yo sigo trabajando en local ... si no sabes cómo echarlo a andar lo intento yo
chaooooo!

**Comment by migueldiaz** [comment]
Hombreee, estreses ninguno, es que ese me sonaba. Hay que borrar el asociation.rb de la carpeta controllers.
Hay abierto un issue con el tema, en local lo corregi al fin pero por lo que se ve no lo subi al final. 
Ya esta borrado, ahora mismo no tengo ssh. Reiniciando la aplicacion debe funcionar

**Comment by tangrammer** [comment]
guay!
