### ISSUE TITLE
galeria de fotos... falta imagen mini o zoom

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#23]
miguel!!
lo que hablamos de incorporar esta opcion a las paginas... estoy viendo que falta la segunda imagen
¿lo puedes corregir?
gracias pisha!

**Comment by migueldiaz** [comment]
Se incoporo galeria pero no la imagen mini, me pongo a ello.

**Comment by migueldiaz** [comment]
Listo, lo muestro en las vistas de pagina y subo, te aviso antes

**Comment by migueldiaz** [comment]
Ya en repo, en zona de administracion va bien pero en la portada muestra un cuadrito con nimagen vacio ??,

**Comment by migueldiaz** [comment]
Ciero
