### ISSUE TITLE
redireccion de nueva imagen de imagen de galeria de pagina falla!

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#24]
esto
http://desarrollo.quartiersdumonde.org/imagens
da esto
We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

y venía de aquí (form de crear imagen de galeria)
http://desarrollo.quartiersdumonde.org/imagens/new?id=25

y aunque da error el registro y la imagen los graba ok!
así que creo que debe ser un problema de routing o view que no existe 

ERES UN MAQUINA TIO!

**Comment by migueldiaz** [comment]
Del formulario de crear debe ir a mostrar la imagen creada, ahora mismo no soy capaz de reproducir el error.

http://desarrollo.quartiersdumonde.org/imagens me abre bien.
Reviso los logs del servidor a ver que saco en claro

**Comment by migueldiaz** [comment]
Creo que esto ya no sucede, no soy capaz de reproducirlo, lo dejo abierto de momento.
Si tu crees que efectivamente esta solucionado, cerramos
