### ISSUE TITLE
actualizar pagina de pagina en documentacion jeunes se pierde la pagina padre 

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#25]
pues eso ...
la crea bien cuando hay que crearla... es decir que le indica correctamente cual es su pagina padre pero cuando la modifico se pierde la referencia a la pagina padre 

chaooooooo!!!!

**Comment by migueldiaz** [comment]
Jojo , joder van a salir las goteras a ultima hora, lo miro tb

**Comment by migueldiaz** [comment]
Vale esta era una tonteria
En el form de pagina cambio:
 <%= f.hidden_field :pagina_id,:value=>params[:raiz] %>
por
<%= f.hidden_field :pagina_id %>

**Comment by migueldiaz** [comment]
Offtopic , los botons de guardar no estan redirigiendo , creo que es cosa del javascript, pero sin embargo guardan.
¿El git ignore afecta a la carpeta public al completo o solo a parte?

**Comment by tangrammer** [comment]
puede ser por el cambio de prototype a jquery??
lo hice el otro da en la zona de gestin...

El 23 de agosto de 2011 23:34, migueldiaz <
reply@reply.github.com>escribi:

> Offtopic , los botons de guardar no estan redirigiendo , creo que es cosa
> del javascript, pero sin embargo guardan.
> El git ignore afecta a la carpeta public al completo o solo a parte?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/25#issuecomment-1884314

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
No se, lo curioso es que en despliegue tira bien pero en local con la copia clonada no lo hace. 
Lo he notado hoy, por eso decia lo del gitignore, aver si no esta recuperando algo. Funcionar funciona de todas maneras, tiene que ser algo de eso. ya lo intento mirar yo no te preocupes
