### ISSUE TITLE
Seccion documentacion

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#3]
El proyecto tiene una sección de documentación, es igual a la de presentación y proyectos.
Las paginas de los equipos, en actividades también tienen el campo de documentación adicional

Una diferencia de las páginas:  tiene documentación adicional. 

¿Esta documentación adicional se añade a pagina, como un documento mas, mostrándola con los demás documentos?  o se crea un nuevo campo que sea doc_adicional  para pagina?

**Comment by tangrammer** [comment]
Miguel!
no entiendo la pregunta
puedes reformularla?
saludos!

El 8 de agosto de 2011 16:38, migueldiaz <
reply@reply.github.com>escribi:

> El proyecto tiene una seccin de documentacin, es igual a la de
> presentacin y proyectos.
> Las paginas de los equipos, en actividades tambin tienen este hueco de
> documentacin adicional
> 
> Una diferencia:  tiene documentacin adicional.
> 
> Esta documentacin adicional se aade a pagina, como un documento mas,
> mostrndola con los dems documentos?  o se crea un nuevo campo que sea
> docacional  para pagina?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/3

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Ok, en la pagina original ademas de presentacion y proyectos dentro de un proyecto.
Se muestra una pagina como en los demas sitios , pero aqui aparece una parte de la pagina que es documentacion adicional. 
En algunos equipos tambien aparece. 

Esa parte de documentacion se me quedo atras pero eso no es problema. 

Esa documentacion adicional. ¿Como la añado o como la muestro, o mas bien como distingo la documentacion adicional de la principal.?

**Comment by tangrammer** [comment]
me parece que te refieres a...
http://quartiersdumonde.org/esp/qdm/barcelona/info.php?id=51&id2=227

  Ms informaciones relacionadas con
Documentacinhttp://quartiersdumonde.org/esp/qdm/barcelona/info.php?id=51

> Diagnstico local http://quartiersdumonde.org/esp/qdm/barcelona/info.php?id=51&id2=186
> Documento de sistematizacin ao 1 http://quartiersdumonde.org/esp/qdm/barcelona/info.php?id=51&id2=200
> Sistematizacin Tercer ao http://quartiersdumonde.org/esp/qdm/barcelona/info.php?id=51&id2=260

no???
en realidad es un texto(parrafo con titulo) y enlaces escritos a mano...
creo que no hay que cambiar nada... si el usuario/admin/equipo quiere
incluir enlaces "a mano" de docs existentes que lo haga de esa forma que
queda mu  bien

se aclar la duda???

El 8 de agosto de 2011 18:41, migueldiaz <
reply@reply.github.com>escribi:

> Ok, en la pagina original ademas de presentacion y proyectos dentro de un
> proyecto.
> Se muestra una pagina como en los demas sitios , pero aqui aparece una
> parte de la pagina que es documentacion adicional.
> En algunos equipos tambien aparece.
> 
> Esa parte de documentacion se me quedo atras pero eso no es problema.
> 
> Esa documentacion adicional. Como la aado o como la muestro, o mas bien
> como distingo la documentacion adicional de la principal.?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/3#issuecomment-1755733

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Cierro el tema
