### ISSUE TITLE
Traspaso de información equipos

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#39]
...

**Comment by tangrammer** [comment]
voy por actividades de bamako...
hay que reordenar documentacion por diagnostico local...
directamente contra mysql

**Comment by migueldiaz** [comment]
Juan si quieres dejame a mi algun equipo y migro tambien yo algo

**Comment by tangrammer** [comment]
Gracias tio pero prefiero que acabes tareas de programacion
Estoy en el tren cadiz sevilla y sigo pa punta
.... ofu!

El 26/08/2011 16:12, "migueldiaz" <
reply@reply.github.com>
escribi:

Juan si quieres dejame a mi algun equipo y migro tambien yo algo

##

**Comment by migueldiaz** [comment]
Se te van a caer los pelos con tanto jaleo. 
Como quieras el foro quiero dejarlo cerrado a lo largo de la tarde.
Lo del java, ¿ los de guebs han confirmado que no contemos con él o les mando correo por si se puede instalar?

**Comment by migueldiaz** [comment]
Lo del java, lo averiguo yo, ya mande correo. Hoy intento montar las dos alternativas devise y la nueva fuera a ver como tiran en una cosa simple.

**Comment by tangrammer** [comment]
bamako finalizado!
sigo por barcelona

**Comment by tangrammer** [comment]
voy por Bogotá!

**Comment by tangrammer** [comment]
voy por el alto!

**Comment by tangrammer** [comment]
estoy hasta los huevos
voy por evry!

**Comment by tangrammer** [comment]
sigo hasta los cataplines
voy por montrueil
hoy liquido por cojoneeeeee

**Comment by migueldiaz** [comment]
Jaja, tioo me tenias que haber dejado a mi alguno, que eso es mu coñazo

**Comment by tangrammer** [comment]
faltan pikine, rio y salé!

**Comment by migueldiaz** [comment]
Si quieres delega alguno. Dime cuales y yo los paso

**Comment by tangrammer** [comment]
a tomá viento la isuue de los cojoneeee

**Comment by migueldiaz** [comment]
Esta te pudo, jaja di que si fuera que da mucha alegria cerrarlas
