### ISSUE TITLE
Traspaso de información de foros

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#41]
vamos a ver como mantenemos modelo anterior ... con campos nulos ...?

**Comment by tangrammer** [comment]
ya están puestos los documentos de jeunes faltan femmes y tos los comentarios....

**Comment by tangrammer** [comment]
faltn las descripciones!

**Comment by tangrammer** [comment]
esperando por la gestion activa en servidor.....................

**Comment by tangrammer** [comment]
descripciones de foro jeunes incluidas faltan docs

**Comment by tangrammer** [comment]
incluida informacion de foro jeunes:espacio publico

ofuuuu que coñazo!!!

**Comment by tangrammer** [comment]
que bien que acabo de ver que los usuarios a parte del identificativo en el foro antiguo tienen un enlace a a su mail con lo cual los puedo tener sin duplicados

**Comment by tangrammer** [comment]
mails corregido y sigo por Rencontre internationale des jeunes à Dakar:

**Comment by tangrammer** [comment]
sería correcto que desde la zona de administración se verifique que no existe un usuario con ese mail

**Comment by migueldiaz** [comment]
Me meto donde no me llaman, :P. pero en app/model/usuarioforo.rb se hace añadiendo la línea:
<code> validates_uniqueness_of :email </code>

**Comment by tangrammer** [comment]
Ole!

El 19/09/2011 21:16, "Miguel" <
reply@reply.github.com>
escribi:

Me meto donde no me llaman, :P. pero en app/model/usuarioforo.rb se hace
aadiendo la lnea:
<code> validates_uniqueness_of :email </code>

##

**Comment by migueldiaz** [comment]
En el modelo de usuario hay varias validaciones y en pagina y parrafo algunas personalizadas, por si te valen

**Comment by tangrammer** [comment]
voy por foro construccion social del territorio!
ofuuuuuuuuuuuuuuuu

**Comment by tangrammer** [comment]
en foros joves: daniele y equipo rio es la misma persona ¿qué hago?

**Comment by tangrammer** [comment]
dejar usuario unico grainesenegal@gmail.com ahora está repetidoooo

**Comment by tangrammer** [comment]
tengo una ghilman.qdm@gmail.com y ahora aparece jamilalife@hotmail.com ... es la misma???

**Comment by tangrammer** [comment]
esto esta mal traducido
http://quartiersdumonde.org/esp/qdm/foros.php?id_foro01=428&open_01=428&open_02=&id=31&days=10000#gotoforum

**Comment by tangrammer** [comment]
joves completo!

**Comment by tangrammer** [comment]
he pasado las issues de revision de info a #35 y se da por finalizado el trasvase de información!
