### ISSUE TITLE
diseño de tipos avanzados con Lettering.js

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#43]
intentando hacer algo así como...

<table style="width:auto;"><tr><td><a href="https://picasaweb.google.com/lh/photo/CBjipwGik54-l6GaazK7rg?feat=embedwebsite"><img src="https://lh6.googleusercontent.com/-E1JLOHizpmM/TgA2wnV_bCI/AAAAAAAACtQ/emyqSHlFBR0/s144/qdm_multiverso_110620_120133_0002.jpg" height="102" width="144" /></a></td></tr><tr><td style="font-family:arial,sans-serif; font-size:11px; text-align:right">De <a href="https://picasaweb.google.com/juanantonioruz/Qdm?authuser=0&feat=embedwebsite">qdm</a></td></tr></table>

**Comment by migueldiaz** [comment]
cuando liquidemos esto tenemos que quedar un dia y me tienes que dar una intro al js.

**Comment by tangrammer** [comment]
pos claro que si hombre!
a ver si conseguimos que el proyecto luzca lo suficiente como para convencer
a otro cliente/proyecto para que se lo hagamos!

he estado refinando las issues/milestones/labels para que no se nos quede na
en el tintero y organicemos guay la finalizacon del proyecto... por lo
menos que parezca al final que somos organizaos no?

El 24 de agosto de 2011 01:21, migueldiaz <
reply@reply.github.com>escribi:

> cuando liquidemos esto tenemos que quedar un dia y me tienes que dar una
> intro al js.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/43#issuecomment-1885234

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
