### ISSUE TITLE
busquedas en info de la db... 

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#46]
pues eso que busque en titulos, descripciones, paginas, secciones de la db.... y que de los resultados con links a sus respectivos origenes...

**Comment by migueldiaz** [comment]
Desde guebs dicen que hay posibilidad de java, por lo que he leido, el java solo se lanza para indizar documentos, generando unos xml. Si en la busqueda ponemos un checkbox que indique si en la busqueda se incluyen documentos , se reducen las veces que se utiliza. 

La gema: https://github.com/outoftime/sunspot/wiki

PDF y demas fauna: buscar Solr cell (Google), http://wiki.apache.org/solr/ExtractingRequestHandler

Tutorial: https://github.com/outoftime/sunspot/wiki/Adding-Sunspot-search-to-Rails-in-5-minutes-or-less

Tipos de busqueda: https://github.com/outoftime/sunspot/wiki/Setting-up-classes-for-search-and-indexing

**Comment by migueldiaz** [comment]
Monto un ejemplito en local a ver si me quedo con la copla

**Comment by migueldiaz** [comment]
Efectivamente, la opcion de los jar es factible, si se le indica el stored solo usa java en la primera subida

:STORED
Boolean: If true, the values in this field will be stored as well as indexed. When results are retrieved, stored field values are available in Hit objects, and can be accessed without making a database round-trip to populate the actual result instance

**Comment by migueldiaz** [comment]
https://github.com/outoftime/sunspot/wiki/Working-with-search
En particular <code>search = Sunspot.search(Post, Comment)</code>

**Comment by tangrammer** [comment]
que crack!

El 31 de agosto de 2011 23:44, migueldiaz <
reply@reply.github.com>escribi:

> Muy, muy rapido, en local y en development. Montado un modelo de prueba
> simple, mirando la documentacion de los facets para que sea polivalente para
> todos los modelos
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/46#issuecomment-1962383

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Para instalar la gema en repo necesitamos 
<code>sudo yum install -y libxml2 libxml2-devel libxslt libxslt-devel</code>
Acabo de abrir incidencia en guebs para que lo hagan

**Comment by migueldiaz** [comment]
Busqueda indexa los campos de texto de parrafo correctamente.
Hay un metodo auxiliar <code>muestrapagina(parrafo)</code> que devuelve un enlace a la pagina, en el sitio correspodiente.

TODO: Esquema: donde pueden aparecer los resultados de una busqueda: parrafos, imagenes, comentarios, foros,... ????
En los resultados como formateo los resultados de la busqueda (HIGHLIGHT ??)  ..

Para los documentos --> tituloes , titulofr, mostrarlos en  su contexto y un enlace directamente en busqueda?
...

**Comment by migueldiaz** [comment]
Para indexar datos ya existentes <code> rake sunspot:reindex</code>
Al indexar campos , cuidado con la visibilidad

-Parrafos --> busqueda en todos los campos de texto, muestra enlace a la pagina que lo contiene
-Paginas --> busqueda por titulos . Enlace al path (jeunes,femmes,.. ) de la pagina (aqui entraran las presentaciones, proyectos, no le veo sentido a meter busqueda por seccion cuando las secciones no tienen titulo.)
-Equipos -> Busqueda por nombre y descripcion, muestra enlace al sitio del equipo
-Documentos-> Busqueda por nombre del documento, de momento muestra el enlace al documento

**Comment by migueldiaz** [comment]
Extraer el formulario de busqueda , recuperarlo con un render.
Mostrar opciones de busqueda: documentos, textos, imagenes,... todos.
Extraer los resultados y mostrarlos tb con render.

**Comment by tangrammer** [comment]
he desplegao en el servidor la ultima version del repo...
 ¿el buscador todavía no da resultados no? ¿hay que indexar en este momento???

**Comment by migueldiaz** [comment]
El buscador ahora mismo indexa casi todo lo que lleva texto,muestra bien los parrafos y equipos, 
Tengo pendiente completar los helper para busquedas en documentos, contactos y eventos. 
Tengo que copiar tus metodos de asignacion de local para los resultados. 

Si la primera vez tienes que hacer reindex, en el wiki, puse los pasos .

**Comment by migueldiaz** [comment]
Para que estas en servidor, yo por ssh inicie el servidor de busquedas, de guebs no me han respondido con lo del java. 
Lo miro yo tb.

**Comment by tangrammer** [comment]
pues eso... te dejo a ti "el honor"de lanzar esos comandos ! por si acaso
salta la liebre que veas de que tamao es!

El 8 de septiembre de 2011 18:02, Miguel <
reply@reply.github.com>escribi:

> El buscador ahora mismo indexa casi todo lo que lleva texto,muestra bien
> los parrafos y equipos,
> Tengo pendiente completar los helper para busquedas en documentos,
> contactos y eventos.
> Tengo que copiar tus metodos de asignacion de local para los resultados.
> 
> Si la primera vez tienes que hacer reindex, en el wiki, puse los pasos .
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/46#issuecomment-2041259

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Anda que tienes tarea, voy pal servidor. En local lo pudiste probar?

**Comment by tangrammer** [comment]
nain! lo intente sin indexar! y la respuesta no estaba en routes.rb ....

2011/9/8 Miguel <
reply@reply.github.com>

> Anda que tienes tarea, voy pal servidor. En local lo pudiste probar?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/46#issuecomment-2041298

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
En log tenemos esto
<code>Errno::ECONNREFUSED (Connection refused - connect(2)): app/controllers/busquedas_controller.rb:9:in `index'
</code>
En los tutos dice que suele ser porque el servidor no se inicio, leo a ver si tiene truco como la maldita migracion

**Comment by migueldiaz** [comment]
Alarmas , el java no esta instalado, en google parece ser que viene por hay los tiros. 
las gemas ferret y acts_as_ferret las acabo de instalar sin problemas aparentes. Pero.. estoy leyendo cosas que no me gustan de ferret en produccion y tendriamos que añadir de todas maneras otra cosa cuando queramos indexar texto de documentos. 
Le hecho un vistazo a sphynx que parece estar mas activo y si puedo dejo montada alguna solucion de busqueda hoy.

**Comment by migueldiaz** [comment]
Hay esperanzas, el servidor de búsquedas se lanza con 
<code>rake sunspot:solr:start RAILS_ENV=production</code>
A la hora de hacer el reindex, devuelve <code>getaddrinfo: Name or service not known</code>

**Comment by migueldiaz** [comment]
Info que parece buena: http://groups.google.com/group/rubyonrails-talk/browse_thread/thread/6629b4b9f7e10b5b/7e622f71d171a649

Para lanzar con avisos: <code>rake sunspot:solr:run RAILS_ENV=production --trace
</code>

**Comment by migueldiaz** [comment]
Les abro otra incidencia a los de guebs , para que instalen el java de una vez. Esta noche si o si dejo andando una solucion de busqueda en el servidor, abro un nuevo repo y monto por separado otra alternativa, asi podemos recuperar esta en cuanto nos den noticias.

**Comment by tangrammer** [comment]
Sin prisa tio!

El 08/09/2011 20:46, "Miguel" <
reply@reply.github.com>
escribi:

Les abro otra incidencia a los de guebs , para que instalen el java de una
vez. Esta noche si o si dejo andando una solucion de busqueda en el
servidor, abro un nuevo repo y monto por separado otra alternativa, asi
podemos recuperar esta en cuanto nos den noticias.

##

**Comment by tangrammer** [comment]
lo que te deca ... la entrega funcional ya est bastante presentable! don't
worry, esto est en fase final!

El 8 de septiembre de 2011 20:47, JUAN ANTONIO RUZ <juanantonioruz@gmail.com

> escribi:
> 
> Sin prisa tio!
> 
> El 08/09/2011 20:46, "Miguel" <
> reply@reply.github.com>
> escribi:
> 
> Les abro otra incidencia a los de guebs , para que instalen el java de una
> vez. Esta noche si o si dejo andando una solucion de busqueda en el
> servidor, abro un nuevo repo y monto por separado otra alternativa, asi
> podemos recuperar esta en cuanto nos den noticias.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/46#issuecomment-2043185

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Bueno , tu mandas, de todas maneras voy mirando alternativas.
Es que se me acaba el tiempo, ya te digo. El sabado llevo al niño de 
vuelta, tengo que ver a Gianniy cerrar lo del tpv y el programita. Lunes 
papeleo y jueves empiezo clases, quiero ir cerrando frentes.

**Comment by migueldiaz** [comment]
Habemus Java, me han dicho que esta instalado sin mas , no me han vuelto a referir nada del cambio de plan . Asi que podemos dejar el cambio parado y ponermos en marcha con esto.

**Comment by tangrammer** [comment]
Guay, porque hasta que no cobre no habemus dinerito

El 12/09/2011 14:02, "Miguel" <
reply@reply.github.com>
escribi:

Habemus Java, me han dicho que esta instalado sin mas , no me han vuelto a
referir nada del cambio de plan . Asi que podemos dejar el cambio parado y
ponermos en marcha con esto.

##

**Comment by migueldiaz** [comment]
Odio sorl

**Comment by tangrammer** [comment]
¿what?

**Comment by migueldiaz** [comment]
Lo de indexar documentos va a ser el infierno, si tienes hueco a ver si tu encuentras algo que nos sirva, con guebs atinaste tu mejor que yo

**Comment by migueldiaz** [comment]
Paso issue a la final y la cierro con el cambio de servidor , cambia la manera de instalar las cosas y las soluciones disponibles.
Abro una nueva en cuanto le hinque el diente.
