### ISSUE TITLE
me da la impresion que falla incluir imagen a galeria....

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#48]
echale un vistazo cuando puedas parece que da error al crear y modificar

**Comment by migueldiaz** [comment]
En pagina o subpagina, o en ambas?

**Comment by migueldiaz** [comment]
Ya vi el fallo, esta redirigiendo a imagenes cuando el create deberia ir al show. lo reviso en local

**Comment by migueldiaz** [comment]
En local la copia que acabo de clonar funciona perfectamente. ??
Miro el log del servidor

**Comment by migueldiaz** [comment]
NoMethodError (undefined method `imagenmini_changed?' for #Imagen:0x181cdc08):

Lanzaste la migracion con de añadir imagen mini a la galeria??
No toques nada si quieres la lanzo yo

**Comment by migueldiaz** [comment]
Si estas ponte en el chat hombre y averiguamos antes

**Comment by migueldiaz** [comment]
Solucionado, Juaan sigue el metodo rustico, cargate la carpeta app entera y reemplaza por la que se sube.
De todas maneras, lo siento fallo mío. No cierro más las issues hasta que estén en marcha en servidor si hay cambios en la BDD

**Comment by tangrammer** [comment]
ok!

El 25 de agosto de 2011 01:19, migueldiaz <
reply@reply.github.com>escribi:

> Solucionado, Juaan sigue el metodo rustico, cargate la carpeta app entera y
> reemplaza por la que se sube.
> De todas maneras, lo siento fallo mo. No cierro ms las issues hasta que
> estn en marcha en servidor si hay cambios en la BDD
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/48#issuecomment-1895479

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Habia un segundo fallo que tambien se me habia pasado y ya esta corregido
