### ISSUE TITLE
La carpeta de uploads esta vacia

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#49]
Es cosa tuya o tenemos tragedia?

**Comment by tangrammer** [comment]
ya est repuesta!

2011/8/25 migueldiaz <
reply@reply.github.com>

> Es cosa tuya o tenemos tragedia?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/49

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Vale, no corria prisa , es que he visto todas las imágenes vacías y me ha mosqueado con lo bien que iba
