### ISSUE TITLE
Foros de discusion

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#5]
A ver que te parece el esquema este: http://dl.dropbox.com/u/11666169/foro.png

 ¿Como crees que deberíamos tratar los usuarios? 
¿Se crea un modelo que sea usuarioforo, los metemos en los usuarios del web con un tipo?

Te voy a marear un poco hoy pero me tengo que ir en un rato y no vuelvo hasta tarde. Así esta noche le puedo meter otro empujón

**Comment by tangrammer** [comment]
Oye has echado un vistazo a alguna opcin prefabricada?
http://stackoverflow.com/questions/5354712/im-looking-for-a-rails-3-forum-application
podramos aprovechar algo?
el esquema no lo veo claro, tenemos que chatearlo despus en caso
contrario...
chaoooo!

http://stackoverflow.com/questions/5354712/im-looking-for-a-rails-3-forum-application
El 8 de agosto de 2011 17:06, migueldiaz <
reply@reply.github.com>escribi:

> A ver que te parece el esquema este:
> http://dl.dropbox.com/u/11666169/foro.png
> 
>  Como crees que deberamos tratar los usuarios?
> Se crea un modelo que sea usuarioforo, los metemos en los usuarios del web
> con un tipo?
> 
> Te voy a marear un poco hoy pero me tengo que ir en un rato y no vuelvo
> hasta tarde. As esta noche le puedo meter otro empujn
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/5

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Ok, miro las soluciones prefabricadas, eso ni se me habia pasado por la cabeza.

**Comment by tangrammer** [comment]
## esta opcion del enlace me parece la mejor para empezar

You can check this link for reference :
http://net.tutsplus.com/tutorials/other/building-a-forum-from-scratch-with-ruby-on-rails/

This is not in Rails 3, but I have created an application following the same
in Rails 3 without facing any issue. I agree that many things have been
deprecated in Rails 3, but still you can create an app in it which was

## already implemented in older version.

he bicheado las otras y me da la impresin que van a complejizar la "cosa"
chao!

2011/8/8 migueldiaz <
reply@reply.github.com>

> Ok, miro las soluciones prefabricadas, eso ni se me habia pasado por la
> cabeza.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/5#issuecomment-1755739

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Si a esos mismos, lo los enlaces a mano , no se, son enlaces a archivos del sitio que se han tenido que cargar de una manera , ademas en el titulo va un enlace a la misma pagina.
Veras hacerlo es un momento , era solo por que no recordaba haber visto eso en ningun lado.
Si quieres lo dejo tal como esta, si no ya te digo , lo hago en un momento.

**Comment by tangrammer** [comment]
por ahora no hace falta hacerlo
concentramos esfuerzos en foro!
gracias pischa (se me est pegando el gaditano ya)!!

El 8 de agosto de 2011 18:56, migueldiaz <
reply@reply.github.com>escribi:

> Si a esos mismos, lo los enlaces a mano , no se, son enlaces a archivos del
> sitio que se han tenido que cargar de una manera , ademas en el titulo va un
> enlace a la misma pagina.
> Veras hacerlo es un momento , era solo por que no recordaba haber visto eso
> en ningun lado.
> Si quieres lo dejo tal como esta, si no ya te digo , lo hago en un momento.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/5#issuecomment-1755856

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
