### ISSUE TITLE
galeria de fotos extra para asociacion, jeunnes, femmes y cada equipo...

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#52]
Buenas Miguel!
aquí vengo para darte la tabarra... para variar!
vamos a ver petición: ¿se puede crear galeria de fotos extra para asociacion, jeunnes, femmes y cada equipo... ? la finalidad es poder gestionar desde la zona de gestión las imagenes que salen de fondo (background) en los proyectos/equipos correspondientes

si se puede hacer estaría muy bien darle prioriadad para la entrega funcional del 9 septiembre, de esa forma puedo currar el diseño incluyendo la info en db...

saludos y gracias pisha!

**Comment by migueldiaz** [comment]
Lo que quieres es que el sitio tenga una galeria? Una opcion mas como la presentacion usuarios y demas?

**Comment by tangrammer** [comment]
sip!

2011/8/28 migueldiaz <
reply@reply.github.com>

> Lo que quieres es que el sitio tenga una galeria? Una opcion mas como la
> presentacion usuarios y demas?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/52#issuecomment-1925724

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Estoy en ello como son para los fondos deduzco que no hay piefoto, ni miniatura

**Comment by tangrammer** [comment]
exacto!

2011/8/29 migueldiaz <
reply@reply.github.com>

> Estoy en ello como son para los fondos deduzco que no hay piefoto, ni
> miniatura
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/52#issuecomment-1933119

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Hecho subo a repo y cierro, ojo para despliegue tiene una migracion.

**Comment by tangrammer** [comment]
gracias!!!

El 29 de agosto de 2011 19:01, migueldiaz <
reply@reply.github.com>escribi:

> Hecho subo a repo y cierro, ojo para despliegue tiene una migracion.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/52#issuecomment-1933563

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
