### ISSUE TITLE
documentación foro ..

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#53]
Ey!
¿se podría poner en el wiki "instrucciones de uso de foro" para que lo entendamos nosotros y luego aprovechamos y pasamos a cliente?
la hacemos entre los dos ... y no se trata de esmerarse con fotos sino redactar las instrucciones

saludos

**Comment by migueldiaz** [comment]
Si claro, si quieres dejame acabar la zona del traductor para comentarios y me pongo con ello

**Comment by tangrammer** [comment]
no hurry!

El 28 de agosto de 2011 23:49, migueldiaz <
reply@reply.github.com>escribi:

> Si claro, si quieres dejame acabar la zona del traductor para comentarios y
> me pongo con ello
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/53#issuecomment-1925734

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Mira tienes una especie de boceto en el wiki, dime si es la idea que o documentacion no he redactado nunca.

**Comment by tangrammer** [comment]
perfecto!
y la versin de documentacin para el que usa la gestin de foros y con eso
completamos..
yo le har unos pantallazos cuando tengamos los estilos puestos y listo!

El 29 de agosto de 2011 00:05, migueldiaz <
reply@reply.github.com>escribi:

> Mira tienes una especie de boceto en el wiki, dime si es la idea que o
> documentacion no he redactado nunca.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/53#issuecomment-1925813

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Retocada la pagina. Creada un apartado con indicaciones para la gestión
