### ISSUE TITLE
Traductor Juan

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#55]
Hay un usuario en despliegue paco - paco
Mira si va por ahi los tiros que de esta seccion no hemos hablado. Estoy retocando algunas cosas de lo nuevo y quiero dejarlo cerrado

**Comment by tangrammer** [comment]
la funcionalidad es esa!
se supone que si alguien (admin/equipo/...) hace cambios en algn registro
con traducciones, el registro vuelve a pasar a necesita revisin por parte
de traductor correspondiente...
el tema es que debe haber 2 traductores  uno del esp al fra y otro del fra
al esp e igualmente debera haber 2 check en la base de datos que reflejen
esto...
mu coazo?

El 29 de agosto de 2011 20:55, migueldiaz <
reply@reply.github.com>escribi:

> Hay un usuario en despliegue paco - paco
> Mira si va por ahi los tiros que de esta seccion no hemos hablado. Estoy
> retocando algunas cosas de lo nuevo y quiero dejarlo cerrado
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/55

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
de la vista me encargo yo!
es decir de que el traductor vea los campos correspondientes como editables
...

El 30 de agosto de 2011 00:33, JUAN ANTONIO RUZ
juanantonioruz@gmail.comescribi:

> la funcionalidad es esa!
> se supone que si alguien (admin/equipo/...) hace cambios en algn registro
> con traducciones, el registro vuelve a pasar a necesita revisin por parte
> de traductor correspondiente...
> el tema es que debe haber 2 traductores  uno del esp al fra y otro del fra
> al esp e igualmente debera haber 2 check en la base de datos que reflejen
> esto...
> mu coazo?
> 
> El 29 de agosto de 2011 20:55, migueldiaz <
> reply@reply.github.com>escribi:
> 
> Hay un usuario en despliegue paco - paco
> 
> > Mira si va por ahi los tiros que de esta seccion no hemos hablado. Estoy
> > retocando algunas cosas de lo nuevo y quiero dejarlo cerrado
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/migueldiaz/quartiersRedise-o/issues/55
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programacin gil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Si claro al crear el traductor se indica que idioma traduce, y solo ve los pendientes de traducir en su idioma, casillas solo puse una para indicar que la traducción se ha revisado. Habria que poner la nueva y contemplarlo en los index de todos los controladores que lleven texto. 
Lo de los cambios... si va a ser un poquito coñazo. Le meteré un campo oculto o algo que se ponga a false si pasa por edit un usuario no traductor o algo
Traductor tiene oculta la opción de eliminar en todos los index, el solo ve o edita.

**Comment by migueldiaz** [comment]
Al final lo de que se cambie es una tonteria, entretenido de cambiar pero en fin
<code>
 <%if current_user.tipo=='traductor'%>
   <div class="field">
    <%= f.label t :revisado %><br />
    <%= f.check_box :revisado%>
  </div>
   <div class="field">
    <%= f.label t :revisadofr %><br />
    <%= f.check_box :revisadofr %>
  </div>
  <%else%>
  <div class="field">
     <%= f.hidden_field :revisadofr,:value=>false %>
    <%= f.hidden_field :revisado,:value=>false %>
  </div>
  <%end%>
</code>

**Comment by tangrammer** [comment]
yo me apunto a esta tarea tambin !
as compartimos los pesares!

2011/8/30 migueldiaz <
reply@reply.github.com>

> Al final lo de que se cambie es una tonteria, entretenido de cambiar pero
> en fin
> <%if current_user.tipo=='traductor'%>
>   <div class="field">
>    <%= f.label t :revisado %><br />
>    <%= f.check_box :revisado%>
>  </div>
>  <%else%>
>  <div class="field">
>    <%= f.text_field :revisado,:value=>false %>
>  </div>
>  <%end%>
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/55#issuecomment-1945723

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Da igual, estoy haciendo la lista de tablas que tienen texto , lo entretenido es sacar las migraciones , pero una vez tenga claro cuales son es muy repetitivo. Como toqueteemos los dos lo mismo es mas jaleo para los commit

**Comment by migueldiaz** [comment]
Ok las migraciones hechas, tengo la cabeza espesa, no me acordaba que se podia meter en la misma migracion a todos
Cambio los form e incorporo esas opciones en todos.
Pendiente en el controlador del traductor y en los index de todos si el modo es sin revisar mostrar solo los que sean del traducea del traductor.

**Comment by tangrammer** [comment]
despiertaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa eres un programador feliiiiiz digo
ruby!

El 30 de agosto de 2011 21:13, migueldiaz <
reply@reply.github.com>escribi:

> Ok las migraciones hechas, tengo la cabeza espesa, no me acordaba que se
> podia meter en la misma migracion a todos
> Cambio los form e incorporo esas opciones en todos.
> Pendiente en el controlador del traductor y en los index de todos si el
> modo es sin revisar mostrar solo los que sean del traducea del traductor.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/55#issuecomment-1947253

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Jaja, feliz seré cuando mi cara ya no salga en los issues

**Comment by tangrammer** [comment]
tu no tenas planeao irte pa sevilla en breve?

El 30 de agosto de 2011 21:21, migueldiaz <
reply@reply.github.com>escribi:

> Jaja, feliz ser cuando mi cara ya no salga en los issues
> 
> El 30/08/2011 21:19, juanantonioruz escribi:
> 
> > rtaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa eres un programador feliiiiiz digo
> > ruby!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/55#issuecomment-1947345

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Estuve la semana esa que me iba a ir a Conil. Pero si tengo que ir y 
antes del 15, 3 o 4 días, a ver que pasa al final con Gianni.
Lo que pasa es que esta semana voy a por el niño y lo tengo aquí casi 
hasta el 15.
Quiero rematar lo gordo antes de que llegue
