### ISSUE TITLE
Vistas

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#60]
Mira a lo mejor nos puede interesar, 

https://github.com/mislav/will_paginate/wiki

Lo pongo solo para que lo veas, la gema esta de busquedas tiene muy buena pinta.

**Comment by tangrammer** [comment]
en este proyecto quiz en los foros nos puede ir guay, en el resto no creo
que haya ms de 5 paginas en una seccin as pasen 100 aos!

2011/8/31 migueldiaz <
reply@reply.github.com>

> Mira a lo mejor nos puede interesar,
> 
> https://github.com/mislav/will_paginate/wiki
> 
> Lo pongo solo para que lo veas, la gema esta de busquedas tiene muy buena
> pinta.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/60

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Ok , era solo para que lo vieses, cierro el issue que da mas alegruia que haya menos
