### ISSUE TITLE
como averiguar el path de equipo si es de jeunes o de femmes ???

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#61]
y de esa forma configurar la vista/template...

**Comment by migueldiaz** [comment]
Lo mas rapido en equipe_controller, redefinir el <code>anotherby_method</code> si !@equipo.jeunes.nil? --> layout jeunes ... 
En comentarios_controller o en el foros_controller,  se usa ese metodo para cambiar el template creo. 

Voy al doltol que tengo cita ahora, cuando llegue lo subo yo si quieres.

**Comment by tangrammer** [comment]
gracias y suerte!

El 5 de septiembre de 2011 14:34, migueldiaz <
reply@reply.github.com>escribi:

> Lo mas rapido en equipe_controller, redefinir el
> <code>anotherby_method</code> si !@equipo.jeunes.nil? --> layout jeunes ...
> En comentarios_controller o en el foros_controller,  se usa ese metodo para
> cambiar el template creo.
> 
> Voy al doltol que tengo cita ahora, cuando llegue lo subo yo.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/61#issuecomment-1998910

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
En local funciona esto,

<pre><code>
  
  layout :segun_proyecto
 
  def segun_proyecto
     @equipo=Equipo.find(params[:id])
     if !@equipo.jeunes.nil?
       'juan_jeunes'
     else
       'quartiers'
     end
 end
</code></pre>

**Comment by tangrammer** [comment]
funciona perfecto, gracias!
