### ISSUE TITLE
¿como se configura el tamaño de la imagen que se suben?

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#64]
es una pregunta: no hay que programar nada!
estoy mirando como se especifica el tamaño de la imagen al que se remuestrea las subidas al servidor
lo unico que veo es         <%= f.file_field :imagen %>

creo recordar que se podía especificar no??

chaooooo

**Comment by migueldiaz** [comment]
Se configura en el uploader,   puedes tocar los metodos para que redimensionen, hagan las miniaturas,..
Ahora mismo solo comprueba que lo que se sube sea una imagen.

**Comment by tangrammer** [comment]
what?
uploader? qu es eso y dnde vive?

El 7 de septiembre de 2011 00:26, Miguel <
reply@reply.github.com>escribi:

> Se configura en el uploader,   puedes tocar los metodos para que
> redimensionen, hagan las miniaturas,..
> Ahora mismo solo comprueba que lo que se sube sea una imagen.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/64#issuecomment-2023160

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Esta en <code>app/uploaders/imagen_uploader.rb</code> 
Van en la carpeta esa por la gema de las subidas , carrierwave

**Comment by tangrammer** [comment]
OKI!
voy a cerrar la issue Closes #64

El 7 de septiembre de 2011 00:29, Miguel <
reply@reply.github.com>escribi:

> Esta en <code>app/imagen_uploader.rb</code>
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/64#issuecomment-2023193

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
