### ISSUE TITLE
Template is missing cuando logeo usuario foro de femme

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#65]
parece ser que cuando el usuario se logea/registra al visualizar los foros peta!

Missing template sesionforos/create with {:formats=>[:html], :handlers=>[:rxml, :builder, :rjs, :rhtml, :erb], :locale=>[:es, :es]} in view paths "/home/juanitu/git/quartiersRedise-o/app/views"

pa que te entretengas!

**Comment by migueldiaz** [comment]
Ofu, si entretenido estoy . A ver que ha pasado esa me suena de haberla pasado antes.

**Comment by migueldiaz** [comment]
Linea 15 en sesion_foros_controller:
 <code> elis !usuarioforo.femmes.nil?</code> deberia ser <code> elsif !usuarioforo.femmes.nil?</code>
Solucionado :P

**Comment by tangrammer** [comment]
que hacha!

2011/9/7 Miguel <
reply@reply.github.com>

> Linea 15 en sesion_foros_controller:
>  <code> elis !usuarioforo.femmes.nil?</code> deberia ser <code> elsif
> !usuarioforo.femmes.nil?</code>
> Solucionado :P
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/65#issuecomment-2023392

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
