### ISSUE TITLE
Could not find nokogiri-1.5.0 in any of the sources 

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#67]
no puedo arrancar en local
¿como hago para instalar esto? he intentado sudo gem install nokogiri
pero me lanza error de 

Installing nokogiri (1.5.0) with native extensions /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:533:in `build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

```
    /usr/bin/ruby1.8 extconf.rb 
```

checking for libxml/parser.h... yes
## libxslt is missing.  please visit http://nokogiri.org/tutorials/installing_nokogiri.html for help with installing dependencies.

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby1.8
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --with-iconv-dir
    --without-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-xml2-dir
    --without-xml2-dir
    --with-xml2-include
    --without-xml2-include=${xml2-dir}/include
    --with-xml2-lib
    --without-xml2-lib=${xml2-dir}/lib
    --with-xslt-dir
    --without-xslt-dir
    --with-xslt-include
    --without-xslt-include=${xslt-dir}/include
    --with-xslt-lib
    --without-xslt-lib=${xslt-dir}/lib

Gem files will remain installed in /home/juanitu/.bundler/tmp/14491/gems/nokogiri-1.5.0 for inspection.
Results logged to /home/juanitu/.bundler/tmp/14491/gems/nokogiri-1.5.0/ext/nokogiri/gem_make.out
    from /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:486:in `each'
    from /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:486:in`build_extensions'
    from /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:159:in `install'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/source.rb:96:in`install'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/installer.rb:55:in `run'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12:in`each'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12:in `each'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/installer.rb:44:in`run'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/installer.rb:8:in `install'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/cli.rb:225:in`install'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/task.rb:22:in `send'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/task.rb:22:in`run'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor.rb:246:in`dispatch'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/base.rb:389:in `start'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.12/bin/bundle:13
    from /usr/bin/bundle:19:in`load'
    from /usr/bin/bundle:19
juanitu@juanitu:~/git/quartiersRedise-o$ rails s
Could not find nokogiri-1.5.0 in any of the sources
juanitu@juanitu:~/git/quartiersRedise-o$ ^C
juanitu@juanitu:~/git/quartiersRedise-o$ sudo gem install nokogiri
Fetching: nokogiri-1.5.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
    ERROR: Failed to build gem native extension.

```
    /usr/local/rvm/rubies/ruby-1.9.2-head/bin/ruby extconf.rb
```

checking for libxml/parser.h... yes
## libxslt is missing.  please visit http://nokogiri.org/tutorials/installing_nokogiri.html for help with installing dependencies.

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/rvm/rubies/ruby-1.9.2-head/bin/ruby
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --with-iconv-dir
    --without-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-xml2-dir
    --without-xml2-dir
    --with-xml2-include
    --without-xml2-include=${xml2-dir}/include
    --with-xml2-lib
    --without-xml2-lib=${xml2-dir}/lib
    --with-xslt-dir
    --without-xslt-dir
    --with-xslt-include
    --without-xslt-include=${xslt-dir}/include
    --with-xslt-lib
    --without-xslt-lib=${xslt-dir}/lib

Gem files will remain installed in /usr/local/rvm/gems/ruby-1.9.2-head/gems/nokogiri-1.5.0 for inspection.
Results logged to /usr/local/rvm/gems/ruby-1.9.2-head/gems/nokogiri-1.5.0/ext/nokogiri/gem_make.out

**Comment by tangrammer** [comment]
ya lo arregle en local quitando la dependencia pero me tienes que decir como instal aqui
cuando puedas ... sin prisa, of course!

**Comment by tangrammer** [comment]
pues no, que no furula!
mi arma le estás dando emoción a la entrega! arsa!

**Comment by tangrammer** [comment]
que aventura hacer un revert en git
he tenido que hacer un git reset --hard HEAD y despues un revert  a la versión correspondiente

el git es complicaillo no?

**Comment by migueldiaz** [comment]
Illo, esa se quedo atras al meter el wiki,
Necesitas instalar:
sudo apt-get install libxslt1-dev libxml2-dev

Luego instalas la gema sin problemas, la proxima conectate y te lo digo 
en un momento , que no habia visto tu correo

**Comment by tangrammer** [comment]
guau!
