### ISSUE TITLE
buscador lo he pasado a jeunes/buscador

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#68]
antes de cambiarlo daba error al buscar... me imagino que tengo que hacer configuración adicional

este es el error:

*\* Invoke sunspot:reindex (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute sunspot:reindex
rake aborted!
Connection refused - connect(2)

**Comment by migueldiaz** [comment]
Si hay que lanzar el servidor, y cada vez que añades un modelo hacer el 
reindex, pongo el wiki busquedas mas detallado.
Ahora que lo has mirado , que me quede claro a ver si me estoy yo 
complicando la vida de mala manera. Cuadno quieres buscar documentos, 
entiendo que también quieres alcanzar el texto de dentro del documento. 
Esto es, si es un pdf y en la linea x te habla de feminismo tu quieres 
poder encontrar esa linea , o no?

**Comment by tangrammer** [comment]
correcto!!

El 7 de septiembre de 2011 23:25, Miguel <
reply@reply.github.com>escribi:

> Si hay que lanzar el servidor, y cada vez que aades un modelo hacer el
> reindex, pongo el wiki busquedas mas detallado.
> Ahora que lo has mirado , que me quede claro a ver si me estoy yo
> complicando la vida de mala manera. Cuadno quieres buscar documentos,
> entiendo que tambin quieres alcanzar el texto de dentro del documento.
> Esto es, si es un pdf y en la linea x te habla de feminismo tu quieres
> poder encontrar esa linea , o no?
> 
> El 07/09/2011 23:22, juanantonioruz escribi:
> 
> > antes de cambiarlo daba error al buscar... me imagino que tengo que hacer
> > configuracin adicional
> > 
> > este es el error:
> > 
> > *\* Invoke sunspot:reindex (first_time)
> > *\* Invoke environment (first_time)
> > *\* Execute environment
> > *\* Execute sunspot:reindex
> > rake aborted!
> > Connection refused - connect(2)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/68#issuecomment-2033900

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Mmm, entonces vamos bien con esta gema , es casi la unica alternativa 
asequible, ferret para eso no tiene documentacion y la otra alternativa 
de sphynx 3/4 de lo mismo

**Comment by migueldiaz** [comment]
Cierro esto y sigo en la que habia abierta de busquedas.
Paso las instrucciones al wiki. 
Si ves que con el wiki no tira, reabre esta
