### ISSUE TITLE
crear equipo en mujer peta!

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#70]
esta es la url:
http://localhost:3000/equipos/new?id=3

NoMethodError in EquiposController#create

undefined method `closed?' for nil:NilClass
Rails.root: /home/juanitu/git/quartiersRedise-o

Application Trace | Framework Trace | Full Trace
app/controllers/equipos_controller.rb:43:in `create'
Request

Parameters:

{"commit"=>"Guardar",
 "authenticity_token"=>"wmPMVOhatpEEQB3enH5hl5d92LtJrRF6tDOgQ1L349s=",
 "utf8"=>"\342\234\223",
 "equipo"=>{"revisado"=>"false",
 "jeunes_id"=>"",
 "nombre"=>"asfd",
 "revisadofr"=>"false",
 "descripcionFr"=>"asdf",
 "descripcionEs"=>"asdf",
 "femmes_id"=>"1"}}

**Comment by migueldiaz** [comment]
Retoño acostado, soy todo tuyo, las issues ultimas no estan saliendo en 
el milestone de entrega funcional.
Clono tu ultima subida, y miro sobre esa.

**Comment by migueldiaz** [comment]
En local con la copia ultima de repo llevo 5 equipos creados y ningun fallo, no se que puede ser

**Comment by tangrammer** [comment]
sigue petando en server!

**Comment by tangrammer** [comment]
acabo de probarlo...que cosa más rara tio!

**Comment by migueldiaz** [comment]
En el log tenemos de error <code>Errno::ECONNREFUSED (Connection refused - connect(2)):
  app/controllers/equipos_controller.rb:43:in `create'</code>, que es por el querido sorl. 
Comento las lineas:

<pre>
 #searchable do
  #         text :nombre
  #         text :descripcionEs
  #         text :descripcionFr
  #  end
</pre>

Lo voy comentando en los demas, que tengan definida la busqueda. 
He detectado una cosa nueva, no deja eliminar equipo en mujeres lo miro

**Comment by migueldiaz** [comment]
Solucionado el eliminar equipos. 
Comentados todos los searchable

**Comment by migueldiaz** [comment]
Nota: En local aunque el server de busqueda este desactivado no tenemos este tipo de error,
iran por ahi los tiros ? Alguna configuracion especial en servidor?
