### ISSUE TITLE
CONSULta rapida! me das un consejo para hacer el trasnvase de info del foro antiguo al foro nuevo

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#72]
Pues eso...
voy a empezar a migrar la info de los foros ... ¿cómo crees que lo puedo hacer mejor? directamente contra la db/mysql? o a traves de admin...

gracias tron!

**Comment by migueldiaz** [comment]
Jaja, la semilla Juan, hoy por fin la vas a conocer, eso creo que es lo 
mas facil.
Irte al seed.rb y hacerlo desde ahi.
Mira el modelo de comentario e introduce segun la estructura actual.

**Comment by tangrammer** [comment]
Ostras!

El 08/09/2011 18:12, "Miguel" <
reply@reply.github.com>
escribi:

Jaja, la semilla Juan, hoy por fin la vas a conocer, eso creo que es lo
mas facil.
Irte al seed.rb y hacerlo desde ahi.
Mira el modelo de comentario e introduce segun la estructura actual.

El 08/09/2011 18:09, juanantonioruz escribi:

> Pues eso...
> voy a empezar a migrar la info de los foros ... cmo crees que lo puedo
> hacer mejor? directamente contra la db/mysql? o a traves de admin...
> 
> gracias tron!

##

**Comment by migueldiaz** [comment]
Al final no es para temerla, fue un atranque tonto que se junto con 10 
mas  :P
En el mismo seed vienen un par de ejemplos.
Haz un par de pruebas en local de un comentario y su respuesta y tu ves 
como es mas facil, despues sera copiar eso una y otra vez.
Para cargar los datos en local rake db:seed

**Comment by tangrammer** [comment]
no me convence la semilla tio!
lo hago a través del mysql
el seed es para recreación pero yo quiero only una recreación

**Comment by migueldiaz** [comment]
Como te sea mas comodo. Si quieres podemos añadir un nombre al 
comentario en la bd para mostrar un usuario facil.

**Comment by tangrammer** [comment]
oye que tiene que ver la tabla usuarios con la de usuarioforos?

El 8 de septiembre de 2011 21:24, Miguel <
reply@reply.github.com>escribi:

> Como te sea mas comodo. Si quieres podemos aadir un nombre al
> comentario en la bd para mostrar un usuario facil.
> 
> El 08/09/2011 21:22, juanantonioruz escribi:
> 
> > no me convence la semilla tio!
> > lo hago a travs del mysql
> > el seed es para recreacin pero yo quiero only una recreacin
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043598

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Nada,usuarios es del sitio y la otra de los fotos
El 08/09/2011 21:47, "juanantonioruz" <
reply@reply.github.com>
escribi:

**Comment by tangrammer** [comment]
quillo podemos tener en gestin la opcion de gestion de usuariosforo y
comentarios de foro al igual que el resto de las entidades...
esto es un infierno con las claves salt, los foros de sitio, los comentarios
que responden a otro comentario ... no me siento las piernas tio!
y de todas formas ... puedes repasarlo un poco porque no estoy seguro si el
comportamiento desde gestin es lgico: cuando pico en comentarios me sale
el registro de usuario del foro???

El 8 de septiembre de 2011 21:48, Miguel <
reply@reply.github.com>escribi:

> Nada,usuarios es del sitio y la otra de los fotos
> El 08/09/2011 21:47, "juanantonioruz" <
> reply@reply.github.com>
> escribi:
> 
> > oye que tiene que ver la tabla usuarios con la de usuarioforos?
> > 
> > El 8 de septiembre de 2011 21:24, Miguel <
> > reply@reply.github.com>escribi:
> > 
> > > Como te sea mas comodo. Si quieres podemos aadir un nombre al
> > > comentario en la bd para mostrar un usuario facil.
> > > 
> > > El 08/09/2011 21:22, juanantonioruz escribi:
> > > 
> > > > no me convence la semilla tio!
> > > > lo hago a travs del mysql
> > > > el seed es para recreacin pero yo quiero only una recreacin
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043598
> 
> > ## 
> > 
> > Juan Antonio Ruz
> > 
> > enJava.com = programacin gil
> > http://enJava.com
> > info@enjava.com
> > juanantonioruz@gmail.com
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043845
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043863

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Claro, dame una hora y lo hablamos
El 08/09/2011 21:57, "juanantonioruz" <
reply@reply.github.com>
escribi:

**Comment by tangrammer** [comment]
olvidalo!
lo har progresivamente desde la interfaz web dando de alta usuarios y
comentarios ... como un tio vamos!

antes me estaba haciendo la picha un lio pero es por otra cosa...

gracias y perdona el coazo tio!

El 8 de septiembre de 2011 22:01, Miguel <
reply@reply.github.com>escribi:

> Claro, dame una hora y lo hablamos
> El 08/09/2011 21:57, "juanantonioruz" <
> reply@reply.github.com>
> escribi:
> 
> > quillo podemos tener en gestin la opcion de gestion de usuariosforo y
> > comentarios de foro al igual que el resto de las entidades...
> > esto es un infierno con las claves salt, los foros de sitio, los
> > comentarios
> > que responden a otro comentario ... no me siento las piernas tio!
> > y de todas formas ... puedes repasarlo un poco porque no estoy seguro si
> > el
> > comportamiento desde gestin es lgico: cuando pico en comentarios me sale
> > el registro de usuario del foro???
> > 
> > El 8 de septiembre de 2011 21:48, Miguel <
> > reply@reply.github.com>escribi:
> > 
> > > Nada,usuarios es del sitio y la otra de los fotos
> > > El 08/09/2011 21:47, "juanantonioruz" <
> > > reply@reply.github.com>
> > > escribi:
> > > 
> > > > oye que tiene que ver la tabla usuarios con la de usuarioforos?
> > > > 
> > > > El 8 de septiembre de 2011 21:24, Miguel <
> > > > reply@reply.github.com>escribi:
> > > > 
> > > > > Como te sea mas comodo. Si quieres podemos aadir un nombre al
> > > > > comentario en la bd para mostrar un usuario facil.
> > > > > 
> > > > > El 08/09/2011 21:22, juanantonioruz escribi:
> > > > > 
> > > > > > no me convence la semilla tio!
> > > > > > lo hago a travs del mysql
> > > > > > el seed es para recreacin pero yo quiero only una recreacin
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043598
> 
> > > > ## 
> > > > 
> > > > Juan Antonio Ruz
> > > > 
> > > > enJava.com = programacin gil
> > > > http://enJava.com
> > > > info@enjava.com
> > > > juanantonioruz@gmail.com
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043845
> 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043863
> 
> > ## 
> > 
> > Juan Antonio Ruz
> > 
> > enJava.com = programacin gil
> > http://enJava.com
> > info@enjava.com
> > juanantonioruz@gmail.com
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043951
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/72#issuecomment-2043976

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Tio, sal de la oscuridad y ponte al messenger y tardamos menos
