### ISSUE TITLE
regalito: el login de usuario foro no da permiso para ver los foros del otro sitio

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#73]
me acabo de registrar en el foro de jeunes y "sorpresa!" puedo ver los de femmes!
nooooooooooo!!!!
además me da la impresión que no hay un enlace para salir del registro de foros (salir de sesion)

**Comment by migueldiaz** [comment]
Vale, esto andaba en su momento en local tampoco me va ahora.

**Comment by migueldiaz** [comment]
Me he aventurado y te he puesto la opcion de desconectar en views/shared/menu_idioma.html.erb

Es el siguiente codigo:
<code>
  <li>
          <%if usuarioforologado%>
    <%= link_to t('desconectar'),desconectar_url  %> 
    <%end%>
</code>

**Comment by migueldiaz** [comment]
Solucionado en la ultima subida
