### ISSUE TITLE
caspitas! incluir documento a foro peta! 

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#74]
desde local y desde servidor

ahí la llevas titi!

**Comment by migueldiaz** [comment]
En el modelo de documentos, y casi todos si el servidor de indexacion no 
esta en marcha tira el error ese
de Conection Refused Solucion: Cargarnos en los modelos o comentar

searchable do
            text :doces
            text :docfr
   end

**Comment by migueldiaz** [comment]
He comentado en servidor y reinicie , ya carga documentos bien

**Comment by tangrammer** [comment]
gracias voy subiendo docs!

2011/9/8 Miguel <
reply@reply.github.com>

> He comentado en servidor y reinicie , ya carga documentos bien
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/74#issuecomment-2044563

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
