### ISSUE TITLE
foro lleva campo descripción!

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#75]
pue eso!

**Comment by migueldiaz** [comment]
fin de fiesta emocionante, voy

**Comment by migueldiaz** [comment]
En la zona de administracion ya existen los dos campos,
descripciones, descripcionfr. 
Lo saco yo a la vista principal o es cosa tuya?

**Comment by tangrammer** [comment]
Me lo pido

El 08/09/2011 23:22, "Miguel" <
reply@reply.github.com>
escribi:

En la zona de administracion ya existen los dos campos,
descripciones, descripcionfr.
Lo saco yo a la vista principal o es cosa tuya?

##

**Comment by migueldiaz** [comment]
Cierro la issue si has hecho las migraciones en el servidor esto ya debe estar en marcha
