### ISSUE TITLE
incluir coordenadas para posicionamiento en mapa de participaciones de equipos 

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#79]
petición mu fácil!
incluir 2 campos en equipo:
coordenadax y coordenada y para posicionamiento de equipos y foros en los mapitas!

**Comment by migueldiaz** [comment]
El equipo tiene una coordenada x e y. 
Es así?
Formato debe ser: entero o real?

**Comment by tangrammer** [comment]
Sip! Y si me pones en el wiki documentacio aprendo pa la siguiente!

El 14/09/2011 13:31, "Miguel" <
reply@reply.github.com>
escribi:

El equipo tiene una coordenada x e y.
Es as?

##

**Comment by migueldiaz** [comment]
ok,  tenia las notificaciones de correo apagadas y no te vi, esta tarde 
me dedico a eso

**Comment by migueldiaz** [comment]
Subido en el ultimo commit.
Aqui tienes el wiki:
https://github.com/migueldiaz/quartiersRedise-o/wiki/A%C3%B1adir-coordenadas-a-los-equipos

**Comment by tangrammer** [comment]
uf! menuda cosa que me he enterao... tiembla proyecto!

2011/9/14 Miguel <
reply@reply.github.com>

> Subido en el ultimo commit.
> Aqui tienes el wiki:
> 
> https://github.com/migueldiaz/quartiersRedise-o/wiki/A%C3%B1adir-coordenadas-a-los-equipos
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/79#issuecomment-2094206

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
No te me embales que nos conocemos, que yo sigo con las busquedas del 
demonio y a ver si no lo voy a reconocer.
