### ISSUE TITLE
otra migracion: usuario foro tiene es de un equipo

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#85]
Hola MIguel!
mira: para los super foros interactivos necesitaría que el usuario del foro se relacionara con el equipo, en una relacion muchos usuariosforos a 1 equipo, 1 equipo muchos usuariosforos...
en la clase usuarioforo deberia haber una propiedad equipo y en equipo una coleccion de usuarios foro...
en el formulario de alta de usuarios foro que salga un desplegable con los equipos disponibles (jeunes o femmes) y que se seleccione dicha opcion al incluir nuevo usuario... 
yo me encargo del formulario, pero necesitaria que me hicieras la migración de este tipo de propiedades...  (si me lo pones en el wiki te lo agradezco tio!) 

gracias!!

**Comment by migueldiaz** [comment]
Listo, tenia menos tarea de la que creia

https://github.com/migueldiaz/quartiersRedise-o/wiki/A%C3%B1adir-equipos-a-usuarios
