### ISSUE TITLE
Wiki foros

### ISSUE THREAD

**Issue by migueldiaz** [migueldiaz/quartiersRedise-o#87]
Hacker, con el cambio en los foros habra que rehacer el wiki. 
Ahora tengo un par de horas libres , si no por la tarde si estoy disponible para lo que sea

**Comment by tangrammer** [comment]
esto es para mi! yo ya me hago cargo de los foros y si necesito ayuda ya te
digo
gracias!!
PD: durante la maana espero recibir la transferencia y proceder a la tuya
chao!

2011/9/19 Miguel <
reply@reply.github.com>

> Hacker, con el cambio en los foros habra que rehacer el wiki.
> Ahora tengo un par de horas libres , si no por la tarde si estoy disponible
> para lo que sea
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/migueldiaz/quartiersRedise-o/issues/87

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Ok, por la arde estoy yo online hasta luego

El 19 de septiembre de 2011 09:31, juanantonioruz <
reply@reply.github.com>escribi:

**Comment by tangrammer** [comment]
Miguel,
mndales un mail a los de guebs a ver si nos dejan trastear con el java para
ver si nos conviene cambiar de plan

gracias!

El 19 de septiembre de 2011 12:45, Miguel <
reply@reply.github.com>escribi:

> Ok, por la arde estoy yo online hasta luego
> 
> El 19 de septiembre de 2011 09:31, juanantonioruz <
> reply@reply.github.com>escribi:
> 
> > esto es para mi! yo ya me hago cargo de los foros y si necesito ayuda ya
> > te
> > digo
> > gracias!!
> > PD: durante la maana espero recibir la transferencia y proceder a la tuya
> > chao!
> > 
> > 2011/9/19 Miguel <
> > reply@reply.github.com>
> > 
> > > Hacker, con el cambio en los foros habra que rehacer el wiki.
> > > Ahora tengo un par de horas libres , si no por la tarde si estoy
> > > disponible
> > > para lo que sea
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/migueldiaz/quartiersRedise-o/issues/87
> > 
> > ## 
> > 
> > Juan Antonio Ruz
> > 
> > enJava.com = programacin gil
> > http://enJava.com
> > info@enjava.com
> > juanantonioruz@gmail.com
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/migueldiaz/quartiersRedise-o/issues/87#issuecomment-2131061
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/87#issuecomment-2132347

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
ya he actualizado un poco la info

**Comment by migueldiaz** [comment]
El java me parece recordar que con export o algo se puede añadir al path en ubuntu, lo miro, si no reviso si tenemos permisos para opt.
Si no recurro a los de guebs
