### ISSUE TITLE
link volver desde incluir parrafo de documentacion de proyecto jovenes falla

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#9]
al clickear en volver dirige a esta solicitud -> http://desarrollo.quartiersdumonde.org/paginas y 
## muestra este error 404

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

---

chaoooooo!

**Comment by migueldiaz** [comment]
Solucionado,
