### ISSUE TITLE
posibilidad de chat entre usuarios de foro conectados

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#90]

**Comment by migueldiaz** [comment]
Creo que puede ser mas o menos sencilo, me autoasigno.

**Comment by tangrammer** [comment]
ests enganchao!

2011/9/21 Miguel <
reply@reply.github.com>

> Creo que puede ser mas o menos sencilo, me autoasigno.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/90#issuecomment-2153761

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
esto del chat... sería un poco como un salon de chat donde todos van escribiendo ... la información no se persiste, sino que es de aplicación/sesion/evento.... en un extra de funcionalidad se podían crear chats entre 2 usuarios, algo así como conversaciones privadas

y todo esto en realidad no entra en el proyecto sino que es por completar al final.......!

**Comment by migueldiaz** [comment]
Pospuesto, cierro issue si vamos con tiempo reviso juggernaut
