### ISSUE TITLE
Problema de internacionalizacion: idioma portugues

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#91]
Cómo sabe el traductor distinguir esto y donde lo incluye....?

**Comment by migueldiaz** [comment]
En despliegue el I18n.locale parece ir mejor, en development y local a veces no responde al navegador hasta la segunda o tercera recarga de la pagina. Si no solucionamos por ahi, el setLocale deberíamos pasarlo a es-ES y fr-FR

**Comment by tangrammer** [comment]
el problema es otro y no est contemplado en los requisitos del proyecto...
no te preocupes!

El 21 de septiembre de 2011 12:00, Miguel <
reply@reply.github.com>escribi:

> En despliegue el I18n.locale parece ir mejor, en development y local a
> veces no responde al navegador hasta la segunda o tercera recarga de la
> pagina. Si no solucionamos por ahi, el setLocale deberamos pasarlo a es-ES
> y fr-FR
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/91#issuecomment-2154348

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
ok

**Comment by migueldiaz** [comment]
Valeee, el comentario ese en  portugues, no me acordaba
