### ISSUE TITLE
buscador ferret

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#94]
He intentado instalar con 
   gem install ferret
y error!

Fetching: ferret-0.11.6.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ferret:
    ERROR: Failed to build gem native extension.

```
    /usr/local/rvm/rubies/ruby-1.9.2-head/bin/ruby extconf.rb
```

creating Makefile

make
gcc -I. -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/i686-linux -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1 -I. -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -D_FILE_OFFSET_BITS=64  -o stem_UTF_8_english.o -c stem_UTF_8_english.c
gcc -I. -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/i686-linux -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1 -I. -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -D_FILE_OFFSET_BITS=64  -o libstemmer.o -c libstemmer.c
gcc -I. -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/i686-linux -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1 -I. -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -D_FILE_OFFSET_BITS=64  -o mempool.o -c mempool.c
gcc -I. -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/i686-linux -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1 -I. -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -D_FILE_OFFSET_BITS=64  -o stem_ISO_8859_1_portuguese.o -c stem_ISO_8859_1_portuguese.c
gcc -I. -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/i686-linux -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward -I/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1 -I. -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -D_FILE_OFFSET_BITS=64  -o r_search.o -c r_search.c
In file included from r_search.c:2:
/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward/st.h:2:2: warning: #warning use "ruby/st.h" instead of bare "st.h"
In file included from r_search.c:3:
/usr/local/rvm/rubies/ruby-1.9.2-head/include/ruby-1.9.1/ruby/backward/rubysig.h:14:2: warning: #warning rubysig.h is obsolete
r_search.c: In function ‘frt_get_td’:
r_search.c:164: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c:165: error: ‘struct RArray’ has no member named ‘len’
r_search.c: In function ‘frt_td_to_s’:
r_search.c:190: error: ‘struct RArray’ has no member named ‘len’
r_search.c:193: warning: initialization discards qualifiers from pointer target type
r_search.c:202: warning: format ‘%ld’ expects type ‘long int’, but argument 3 has type ‘int’
r_search.c:206: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c:208: warning: initialization discards qualifiers from pointer target type
r_search.c: In function ‘frt_td_to_json’:
r_search.c:283: error: ‘struct RArray’ has no member named ‘len’
r_search.c:294: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘frt_q_to_s’:
r_search.c:392: warning: initialization discards qualifiers from pointer target type
r_search.c: In function ‘frt_mtq_set_dmt’:
r_search.c:626: error: too many arguments to function ‘rb_cvar_set’
r_search.c: In function ‘frt_bc_to_s’:
r_search.c:878: warning: initialization discards qualifiers from pointer target type
r_search.c:884: warning: assignment discards qualifiers from pointer target type
r_search.c:887: warning: assignment discards qualifiers from pointer target type
r_search.c:890: warning: assignment discards qualifiers from pointer target type
r_search.c: In function ‘frt_phq_add’:
r_search.c:1168: error: ‘struct RArray’ has no member named ‘len’
r_search.c:1173: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c:1175: error: ‘struct RArray’ has no member named ‘len’
r_search.c:1176: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘frt_fq_set_dms’:
r_search.c:1429: error: too many arguments to function ‘rb_cvar_set’
r_search.c: In function ‘frt_fq_set_dpl’:
r_search.c:1461: error: too many arguments to function ‘rb_cvar_set’
r_search.c: In function ‘frt_spanmtq_init’:
r_search.c:1594: error: ‘struct RArray’ has no member named ‘len’
r_search.c:1595: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘frt_spannq_init’:
r_search.c:1719: error: ‘struct RArray’ has no member named ‘len’
r_search.c:1720: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c:1720: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘frt_spanoq_init’:
r_search.c:1785: error: ‘struct RArray’ has no member named ‘len’
r_search.c:1786: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c:1786: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘frt_sort_init’:
r_search.c:2280: error: ‘struct RArray’ has no member named ‘len’
r_search.c:2281: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘frt_sea_search_internal’:
r_search.c:2513: warning: format ‘%s’ expects type ‘char _’, but argument 3 has type ‘VALUE’
r_search.c: In function ‘frt_sea_search_each’:
r_search.c:2635: error: ‘rb_thread_critical’ undeclared (first use in this function)
r_search.c:2635: error: (Each undeclared identifier is reported only once
r_search.c:2635: error: for each function it appears in.)
r_search.c: In function ‘frt_sea_highlight’:
r_search.c:2708: warning: initialization discards qualifiers from pointer target type
r_search.c:2709: warning: initialization discards qualifiers from pointer target type
r_search.c:2710: warning: initialization discards qualifiers from pointer target type
r_search.c:2756: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c:2757: error: ‘struct RArray’ has no member named ‘len’
r_search.c: In function ‘frt_ms_init’:
r_search.c:2873: error: ‘struct RArray’ has no member named ‘len’
r_search.c:2875: error: ‘struct RArray’ has no member named ‘len’
r_search.c:2876: error: ‘struct RArray’ has no member named ‘ptr’
r_search.c: In function ‘Init_MultiTermQuery’:
r_search.c:3110: error: too many arguments to function ‘rb_cvar_set’
r_search.c: In function ‘Init_FuzzyQuery’:
r_search.c:3419: error: too many arguments to function ‘rb_cvar_set’
r_search.c:3421: error: too many arguments to function ‘rb_cvar_set’
make: *_\* [r_search.o] Error 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-1.9.2-head/gems/ferret-0.11.6 for inspection.
Results logged to /usr/local/rvm/gems/ruby-1.9.2-head/gems/ferret-0.11.6/ext/gem_make.out

**Comment by migueldiaz** [comment]
Cierro issue , con gandi no vamos a usar ferret
