### ISSUE TITLE
probando gandi

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#95]
http://stuffingabout.blogspot.com/2011/04/installing-rails-3-on-ubuntu-1104.html?showComment=1317114549598#c5389919033653717272

http://www.modrails.com/install.html

Deploying a Ruby on Rails application: an example

Suppose you have a Ruby on Rails application in /somewhere. Add a server block
to your Nginx configuration file, set its root to /somewhere/public, and set
'passenger_enabled on', like this:

   server {
      listen 80;
      server_name www.yourhost.com;
      root /somewhere/public;   # <--- be sure to point to 'public'!
      passenger_enabled on;
   }

And that's it! You may also want to check the Users Guide for security and
optimization tips and other useful information:

  /usr/local/rvm/gems/ruby-1.9.2-p290/gems/passenger-3.0.9/doc/Users guide Nginx.html

Enjoy Phusion Passenger, a product of Phusion (www.phusion.nl) :-)
http://www.modrails.com/

**Comment by tangrammer** [comment]
http://iloo.wordpress.com/2011/08/11/ruby-on-rails-could-not-find-a-javascript-runtime/

could not find javascript runtime ...
editar Gemfile
gem 'execjs'
gem 'therubyracer'
bundle install

**Comment by tangrammer** [comment]
NO ME LO PUEDO CREER 
rails s -p 80
http://92.243.12.18/
FUNCIONA

**Comment by migueldiaz** [comment]
Cierro esto, recordar que al final era un chmod 755 a la carpeta /home/enjava para que passenger tirara
