### ISSUE TITLE
usuario de jeunes y usuario de femes puede repetirse en la realidad

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#98]
es decir el filtro de "no pueden existir dos usuarios de foro con el mismo mail" no debe aplicarse cuando son de proyectos diferentes... es decir hay usuarios implicados en los 2 proyectos y no me deja darlos de alta
HELPPPP

**Comment by migueldiaz** [comment]
Desactivo la validacion de email, la solucion seria hacer una validacion a mano. 
Los usuarios de un proyecto se distinguen por jeunes_id o femmes_id. 
La validacion debe verificar que para los usuarios con jeunes_id!=nil no se repite el mail.

**Comment by migueldiaz** [comment]
Esto, ¿con la desactivación de la validación vale o tengo que hacer yo algo más?

**Comment by tangrammer** [comment]
buenas Miguel,
si desactivamos podemos generar casos de usuarios duplicados a tutipleni,
habra que escribir algo de cdigo para que la unicidad de mail sea solo
para cada proyecto
chaooo

2011/10/26 Miguel <
reply@reply.github.com>

> Esto, con la desactivacin de la validacin vale o tengo que hacer yo algo
> ms?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/migueldiaz/quartiersRedise-o/issues/98#issuecomment-2529051

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Unicidad de mail por proyectos, al crear comprueba que no existe usuario previo con ese email.
