### ISSUE TITLE
no borra usuarioforo.. .debe ser un pegolete!

### ISSUE THREAD

**Issue by tangrammer** [migueldiaz/quartiersRedise-o#99]
al hacer click en borrar manda a pagina de error

**Comment by migueldiaz** [comment]
Puede que sea por el redirect tras el destroy , voy a mirar

**Comment by migueldiaz** [comment]
Valee, no hay método delete, no se como se me pudo quedar atrás, me 
pongo a ello.

**Comment by migueldiaz** [comment]
Ya esta resuelto, en servidor debe estar en marcha, ya subi la copia a repo

**Comment by migueldiaz** [comment]
Cierro issue en el ultimo commit va solucionado
